spring.application.name=first-spring-framework
server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/nani
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root@123
spring.jpa.hibernate.ddl-auto=create